version: '3.8'

services:
  db:
    image: postgres:15
    container_name: anticorrupcion_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: jefatura_gabinete
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./src/database/schema_ddl.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./src/database/seed_data.sql:/docker-entrypoint-initdb.d/2-seed.sql

  pgadmin:
    image: dpage/pgadmin4
    container_name: anticorrupcion_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@portal.gov.ar
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - db

  # El servicio de la App se puede agregar aquí una vez esté listo el Dockerfile
